### ISSUE TITLE
Define Acceptable Decisions

### ISSUE THREAD

**Issue by Ochirsaikhan** [Jacob-Allebach/code-of-conduct#3]
#### Acceptable Conduct

- Team members should consider and discuss all possible ideas of each student before moving forward.
- Decisions should be finalized when a team reaches a majority vote.
- Decisions should not be taken personally, and students should criticize ideas, not team members.

**Comment by Jacob-Allebach** [comment]
Second 2 bullet points should start with "Students should" or "Team members should" instead of "Decisions". Other than that, the points themselves seem good.

**Comment by DlHolland** [comment]
Looks good but you may want to take out the comma after the "and"

**Comment by Ochirsaikhan** [comment]
#### Acceptable Conduct

- Team members should finalize decisions when the team reaches a majority vote.
- Team members should consider and discuss all possible ideas of each student before moving forward.
- Team members should not take final decisions personally and criticize ideas, not team members.
